url: https://dwarftools.github.io
baseurl: /LearnEDFM

# Site settings
title: LearnEDFM
email: gjan@dwarftools.org
description: "LearnEDFM - An open source implementation of the embedded discrete fracture model in MATLAB."


# Team names, titles and social links
people:
- name: Gunnar Jansen
  pic: 1
  position: Lead Developer
  social:
    - title: twitter
      url: https://twitter.com/bmightyg
    - title: stack-overflow
      url: http://stackoverflow.com/users/1371788/gjan

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/learnedfm
  - title: github
    url: https://github.com/dwarftools/LearnEDFM

# Postal address (add as many lines as necessary)
address:
  - line: Rue Emile-Argand 11
  - line: 2000 Neuchâtel
  - line: Switzerland

# Build settings
markdown: kramdown
permalink: pretty
